Made the options more clear.
k8guard/k8guard-start-from-here pull request #12
Opened 2017-05-22 21:13 UTC by mpritter76

2017-05-22 23:29 UTC, milsonian approved these changes

2017-05-23 15:41 UTC, medyagh commented
The new title breaks the the relative links. in the top part.
```
Deploy
Deploy in docker-compose
Deploy in minikube
```
I will merge once you fix the links.

2017-05-23 15:44 UTC, medyagh requested changes
breaks the links see comment on the PR

2017-05-23 16:50 UTC, medyagh approved these changes

2017-05-23 16:50 UTC, medyagh commented
Looks good !

2017-05-23 16:50 UTC, merged